import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import * as PDFDocument from 'pdfkit';

@Injectable()
export class InvoiceService {
    constructor(private prisma: PrismaService) { }

    async findAll(businessId: string) {
        return this.prisma.invoice.findMany({
            where: { businessId },
            include: { client: true },
            orderBy: { createdAt: 'desc' },
        });
    }

    async create(businessId: string, data: any) {
        return this.prisma.invoice.create({
            data: {
                invoiceNumber: data.invoiceNumber,
                amount: parseFloat(data.amount),
                status: data.status || 'DRAFT',
                businessId,
                clientId: data.clientId,
            },
        });
    }

    async findOne(id: string, businessId: string) {
        const invoice = await this.prisma.invoice.findFirst({
            where: { id, businessId },
            include: { client: true, business: true },
        });
        if (!invoice) throw new NotFoundException('Invoice not found');
        return invoice;
    }

    async updateStatus(id: string, businessId: string, status: any) {
        return this.prisma.invoice.updateMany({
            where: { id, businessId },
            data: { status },
        });
    }

    async generatePdf(id: string, businessId: string): Promise<Buffer> {
        const invoice = await this.findOne(id, businessId);

        return new Promise((resolve, reject) => {
            const doc = new PDFDocument({ size: 'A4', margin: 50 });
            const chunks: Buffer[] = [];

            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', (err) => reject(err));

            // Header
            doc
                .fillColor('#444444')
                .fontSize(20)
                .text(invoice.business.name.toUpperCase(), 50, 50)
                .fontSize(10)
                .text('Generated by Client Portal', 50, 80)
                .moveDown();

            // Horizontal Line
            doc.moveTo(50, 100).lineTo(550, 100).stroke('#EEEEEE');

            // Invoice Info
            doc
                .fontSize(15)
                .text(`INVOICE: ${invoice.invoiceNumber}`, 50, 120)
                .fontSize(10)
                .text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, 50, 140)
                .text(`Status: ${invoice.status}`, 50, 155)
                .moveDown();

            // Client Info
            doc
                .fontSize(12)
                .text('BILL TO:', 50, 200)
                .fontSize(10)
                .text(invoice.client.name, 50, 215)
                .text(invoice.client.email, 50, 230)
                .moveDown();

            // Total
            doc
                .fontSize(15)
                .text('TOTAL AMOUNT:', 350, 200)
                .fontSize(25)
                .fillColor('#4F46E5')
                .text(`$${invoice.amount.toFixed(2)}`, 350, 220);

            // Footer
            doc
                .fontSize(10)
                .fillColor('#999999')
                .text('Thank you for your business!', 50, 700, { align: 'center', width: 500 });

            doc.end();
        });
    }
}
